/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/skateboard.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Skateboard = (props) => {
  const { nodes, materials } = useGLTF('./models/skateboard.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.065} position={[0, -0.091, 0]}>
        <mesh geometry={nodes.GB14_Skateboard_M_GB14_Skateboard_0.geometry} material={materials.M_GB14_Skateboard} rotation={[Math.PI / 2, 0, 0]}/>
      </group>
    </group>
  )
}

useGLTF.preload('./models/skateboard.gltf')

export default Skateboard;